name: Go
on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.3
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
        
      - name: Check out into go module dir
        uses: actions/checkout@v1
        
      - name: Download deps
        run: go mod download
        
      - name: Run tests
        run: go test ./...
